server {
    listen 80;

    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location = / {
        return 302 /personalportalen/;
    }

    location /personalportalen/ {
        try_files $uri $uri/ /personalportalen/index.html;
    }

    location /assets/ {
        try_files $uri =404;
    }

    location /api/ {
        proxy_pass http://yarp-gateway:8080/;
    }
}