server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # 🔥 FIX: ta bort prefix
    location /personalportalen/ {
        rewrite ^/personalportalen/(.*)$ /$1 break;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://yarp-gateway:8080/;
    }
}