server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # redirect root
    location = / {
        return 302 /personalportalen/;
    }

    # 🔥 VIKTIG: exakt fallback
    location /personalportalen/ {
        try_files $uri $uri/ /personalportalen/index.html =404;
    }

    # API
    location /api/ {
        proxy_pass http://yarp-gateway:8080/;
    }
}