services:
  sqlserver:
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      SA_PASSWORD: ${SQL_PASSWORD}
    env_file:
      - .env.prod

  auth-api:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/personalportalen/authservice:${IMAGE_TAG}
    build: !reset null
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: Server=sqlserver,1433;Database=AuthDb;User Id=sa;Password=${SQL_PASSWORD};TrustServerCertificate=True;
      ASPNETCORE_URLS: http://+:8080
      ServiceBus__ConnectionString: "Endpoint=sb://portfolio-servicebus.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=t/ulwPS42Hy6QP0mErvExWx3MtFUzTc2W+ASbHE0YZU="
      ServiceBus__TopicName: "user-events"
    env_file:
      - .env.prod

  profile-api:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/personalportalen/profileservice:${IMAGE_TAG}
    build: !reset null
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: Server=sqlserver,1433;Database=ProfileDb;User Id=sa;Password=${SQL_PASSWORD};TrustServerCertificate=True;
      ASPNETCORE_URLS: http://+:8080
      ServiceBus__ConnectionString: "Endpoint=sb://portfolio-servicebus.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=t/ulwPS42Hy6QP0mErvExWx3MtFUzTc2W+ASbHE0YZU="
      ServiceBus__SubscriptionName: "profile-service"
    env_file:
      - .env.prod

  booking-api:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/personalportalen/bookingservice:${IMAGE_TAG}
    build: !reset null
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: Server=sqlserver,1433;Database=BookingDb;User Id=sa;Password=${SQL_PASSWORD};TrustServerCertificate=True;
      ASPNETCORE_URLS: http://+:8080
    env_file:
      - .env.prod

  workshift-api:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/personalportalen/workshiftservice:${IMAGE_TAG}
    build: !reset null
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: Server=sqlserver,1433;Database=WorkShiftDb;User Id=sa;Password=${SQL_PASSWORD};TrustServerCertificate=True;
      ASPNETCORE_URLS: http://+:8080
    env_file:
      - .env.prod

  yarp-gateway:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/personalportalen/gateway:${IMAGE_TAG}
    build: !reset null
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
    ports:
      - "5001:8080"
    env_file:
      - .env.prod

  frontend:
    build:
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    ports:
      - "3000:80"
    env_file:
      - .env.prod
