global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "yarp-gateway"
    static_configs:
      - targets: ["yarp-gateway:8080"]

  - job_name: "auth-api"
    static_configs:
      - targets: ["auth-api:8080"]

  - job_name: "profile-api"
    static_configs:
      - targets: ["profile-api:8080"]

  - job_name: "booking-api"
    static_configs:
      - targets: ["booking-api:8080"]

  - job_name: "workshift-api"
    static_configs:
      - targets: ["workshift-api:8080"]
